name: Release container
on:
    pull_request:
        types:
            - closed
        branches:
            - release

jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build Docker image
              run: docker build -t utf-moodle-scraper .
            - name: Add tags to image
              run: |
                  docker tag utf-moodle-scraper zrafaf/utf-moodle-scraper:${{ github.event.pull_request.title }}
                  docker tag utf-moodle-scraper zrafaf/utf-moodle-scraper
            - name: Push Docker image
              run: |
                  docker push zrafaf/utf-moodle-scraper:${{ github.event.pull_request.title }}
                  docker push zrafaf/utf-moodle-scraper
